numpy array are fast convenient less memory insted of list
Numpy is used in syntific and numerical computation

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a[0]

1

# Numpy Operations

 Find dimension of Array


In [ ]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
b=np.array([1,2,3])
print(b.ndim)
print(a.ndim)

2
2


# finding byte size of Array

In [ ]:
print(a.itemsize)

4


In [ ]:
print(a.dtype)

int32


# Finding size of Array

In [ ]:
print(a.size)

6


# finding shape of Array

In [ ]:
print(a.shape)

(2, 3)


In [ ]:
a=np.array([(1,2,3,4),(7,8,9,3)])
a=a.reshape(4,2)
print(a)

[[1 2]
 [3 4]
 [7 8]
 [9 3]]


# Finding Slicing In Array

In [ ]:
a=np.array([(1,2,3,4),(7,8,9,3)])
print(a[0,2])

3


In [ ]:
print(a[0:,3])

[4 3]


In [ ]:
print(a[0:2,3])

[4 3]


# Perform Linespacing in Array

In [ ]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


# Min ,Max ,Sum of Array

In [ ]:
a=np.array([1,2,3,4,5,6,7])
print(a.max())
print(a,min())
print(a.max())

7


# find Axis Row[1] and Colum[0]

In [ ]:
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a.sum(axis=0))
print(a.sum(axis=1))

[ 6  8 10 12]


# Finding square root and Standard deviation

In [ ]:
a=np.array([(1,2,3,4),(5,6,7,8)])
print(np.sqrt(a))
a=np.array([(1,2,3,4),(5,6,7,8)])
print(np.std(a))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
